CREATE FUNCTION getNthHighestSalary(N IN NUMBER) RETURN NUMBER IS
result NUMBER;
BEGIN
    /* Write your PL/SQL query statement below */
    SELECT DISTINCT SALARY INTO RESULT
    FROM
    (
        SELECT SALARY, DENSE_RANK() OVER (ORDER BY SALARY DESC) AS DR FROM EMPLOYEE
    ) WHERE DR = N;

    RETURN result;
END;